import { requireAdmin } from './_lib/auth.js';

export default function handler(req,res){
  res.setHeader('Cache-Control','no-store');
  res.setHeader('Content-Type','text/html; charset=utf-8');
  res.setHeader('X-Robots-Tag','noindex, nofollow');
  if(!requireAdmin(req,res))return;
  if(req.method!=='GET')return res.status(405).send('Method not allowed');
  return res.status(200).send(`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>TaxAI Waitlist Admin</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600;700;800&display=swap" rel="stylesheet"><style>
  :root{font-family:Poppins,sans-serif;color:#102e55;background:#f3f7fb}*{box-sizing:border-box}body{margin:0}.bar{background:#041e42;color:white;padding:18px max(18px,calc((100vw - 1180px)/2));display:flex;justify-content:space-between;align-items:center}.bar b span{color:#cc952d}.wrap{max-width:1180px;margin:35px auto;padding:0 18px}.head{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:20px}.head h1{margin:0;font-size:30px}.head p{margin:5px 0 0;color:#60728a;font-size:13px}.actions{display:flex;gap:9px}.btn{border:0;border-radius:8px;padding:11px 14px;font:700 12px Poppins;cursor:pointer;text-decoration:none}.download{background:#cc952d;color:#172b44}.delete{background:#8d2d31;color:#fff}.delete:disabled{opacity:.45}.card{background:#fff;border:1px solid #dbe4ef;border-radius:13px;overflow:auto;box-shadow:0 12px 34px rgba(4,30,66,.07)}table{width:100%;border-collapse:collapse;min-width:850px}th,td{text-align:left;padding:13px;border-bottom:1px solid #e4eaf2;font-size:12px}th{background:#edf3f9;font-size:10px;text-transform:uppercase;letter-spacing:.06em}td:first-child,th:first-child{width:42px;text-align:center}.empty{padding:55px;text-align:center;color:#6c7c90}.status{min-height:20px;margin:12px 0;color:#53677f;font-size:12px}@media(max-width:700px){.head{align-items:stretch;flex-direction:column}.actions{flex-wrap:wrap}.btn{flex:1;text-align:center}}
  </style></head><body><header class="bar"><b>Tax<span>AI</span>.pk</b><span>Private waitlist admin</span></header><main class="wrap"><div class="head"><div><h1>Waitlist entries</h1><p>Entries expire automatically seven days after submission.</p></div><div class="actions"><a class="btn download" href="/api/export">Download CSV</a><button class="btn delete" id="delete" disabled>Delete selected</button></div></div><div class="status" id="status" role="status"></div><div class="card" id="content"><div class="empty">Loading entries…</div></div></main><script>
  const content=document.getElementById('content'),status=document.getElementById('status'),del=document.getElementById('delete');
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function load(){const r=await fetch('/api/leads',{cache:'no-store'});if(!r.ok){content.innerHTML='<div class="empty">Unable to load entries.</div>';return}const {entries}=await r.json();if(!entries.length){content.innerHTML='<div class="empty">No active entries.</div>';del.disabled=true;return}content.innerHTML='<table><thead><tr><th><input id="all" type="checkbox" aria-label="Select all"></th><th>Received</th><th>Name</th><th>WhatsApp</th><th>Email</th><th>Source</th><th>Expires</th></tr></thead><tbody>'+entries.map(e=>'<tr><td><input class="pick" type="checkbox" value="'+e.id+'" aria-label="Select '+esc(e.name)+'"></td><td>'+esc(new Date(e.created_at).toLocaleString())+'</td><td>'+esc(e.name)+'</td><td>'+esc(e.whatsapp)+'</td><td>'+esc(e.email)+'</td><td>'+esc(e.source)+'</td><td>'+esc(new Date(e.expires_at).toLocaleString())+'</td></tr>').join('')+'</tbody></table>';document.getElementById('all').onchange=e=>{document.querySelectorAll('.pick').forEach(x=>x.checked=e.target.checked);sync()};document.querySelectorAll('.pick').forEach(x=>x.onchange=sync);sync()}
  function selected(){return [...document.querySelectorAll('.pick:checked')].map(x=>Number(x.value))}function sync(){del.disabled=!selected().length}
  del.onclick=async()=>{const ids=selected();if(!ids.length||!confirm('Permanently delete '+ids.length+' selected entr'+(ids.length===1?'y':'ies')+'?'))return;del.disabled=true;status.textContent='Deleting…';const r=await fetch('/api/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids})});status.textContent=r.ok?'Selected entries deleted.':'Deletion failed.';await load()};load();
  </script></body></html>`);
}
